/**
 * Publishing Hub v2 — Infrastructure Management Dashboard
 *
 * 앱/사이트를 등록하면 nginx config + systemd service를 자동 생성하고,
 * 대시보드에서 start/stop/restart/logs까지 원클릭으로 관리.
 *
 * API:
 *   GET  /hub/                        → Dashboard UI
 *   GET  /hub/api/manifest            → manifest.json
 *   GET  /hub/api/health              → health check (apps + sites)
 *   GET  /hub/api/stats               → nginx traffic stats
 *   POST /hub/api/apps                → 앱 등록 + nginx + systemd 배포
 *   POST /hub/api/sites               → 사이트 등록
 *   DELETE /hub/api/apps/:name        → 앱 제거
 *   DELETE /hub/api/sites/:name       → 사이트 제거
 *   POST /hub/api/apps/:name/start    → systemd start
 *   POST /hub/api/apps/:name/stop     → systemd stop
 *   POST /hub/api/apps/:name/restart  → systemd restart
 *   GET  /hub/api/apps/:name/logs     → journalctl logs
 *   POST /hub/api/sync                → manifest ↔ infra 동기화
 *   POST /hub/api/nginx/reload        → nginx 강제 reload
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { exec } = require('child_process');

// ════════════════════════════════════════════════════════════
// Constants
// ════════════════════════════════════════════════════════════

const PORT = parseInt(process.env.HUB_PORT || '32400', 10);
const PUBLISHED_DIR = process.env.PUBLISHED_DIR || path.join(os.homedir(), 'workspace/published');
const MANIFEST_PATH = path.join(PUBLISHED_DIR, 'manifest.json');
const SERVICE_PREFIX = 'pub-';
const USER = process.env.HUB_USER || os.userInfo().username;

// Domain and nginx conf path are derived from manifest at runtime
function getNginxConfPath() {
  try {
    const m = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
    const domain = m.domain || 'localhost';
    return `/etc/nginx/sites-available/${domain}`;
  } catch { return '/etc/nginx/sites-available/pub-hub'; }
}

// ════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════

function readManifest() {
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
}

function writeManifest(data) {
  data.updated_at = new Date().toISOString();
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(data, null, 2) + '\n');
}

function json(res, data, status = 200) {
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(data));
}

function readBody(req) {
  return new Promise((resolve) => {
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => {
      try { resolve(JSON.parse(body)); }
      catch { resolve(null); }
    });
  });
}

function run(cmd) {
  return new Promise((resolve) => {
    exec(cmd, { timeout: 15000 }, (err, stdout, stderr) => {
      resolve({
        ok: !err,
        stdout: (stdout || '').trim(),
        stderr: (stderr || '').trim(),
        code: err?.code,
      });
    });
  });
}

function svcName(appName) {
  return `${SERVICE_PREFIX}${appName}.service`;
}

// ════════════════════════════════════════════════════════════
// Nginx Config Generation
// ════════════════════════════════════════════════════════════

function generateAppLocation(app) {
  if (app.name === 'hub') return ''; // hub is hardcoded in template

  const upstream = `http://127.0.0.1:${app.port}`;
  const proxyHeaders = `
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`;

  if (app.access === 'private') {
    return `
    # ── ${app.name} (login required) ──
    location ${app.path} {
        auth_request /internal/auth;
        error_page 401 = @${app.name.replace(/-/g, '_')}_unauth;

        proxy_pass ${upstream}/;${proxyHeaders}
    }

    location @${app.name.replace(/-/g, '_')}_unauth {
        return 302 /?login=required;
    }
`;
  }

  return `
    # ── ${app.name} (public) ──
    location ${app.path} {
        proxy_pass ${upstream}/;${proxyHeaders}
    }
`;
}

function generateNginxConfig(manifest) {
  const appBlocks = manifest.apps
    .filter(a => a.name !== 'hub')
    .map(generateAppLocation)
    .join('');

  const extraBlocks = (manifest.extra_locations || [])
    .map(loc => `
    # ── ${loc.comment} ──
    ${loc.config}
`)
    .join('');

  const domain = manifest.domain || 'localhost';
  return `# ═══════════════════════════════════════════════════════════════
# ${domain} — Auto-generated by Publishing Hub v2
# Last updated: ${new Date().toISOString()}
# DO NOT EDIT MANUALLY — use /hub/ dashboard or API
# ═══════════════════════════════════════════════════════════════

server {
    listen 80;
    server_name ${domain};

    # ── Auth subrequest (Tower JWT check) ──
    location = /internal/auth {
        internal;
        proxy_pass http://localhost:32355/api/auth/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
    }

    # ── Publishing Hub (login required) ──
    location /hub/ {
        auth_request /internal/auth;
        error_page 401 = @hub_unauthorized;

        proxy_pass http://127.0.0.1:${PORT}/hub/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location @hub_unauthorized {
        return 302 /?login=required;
    }
${appBlocks}${extraBlocks}
    # ── Static Sites (public) ──
    location /sites/ {
        alias ${PUBLISHED_DIR}/sites/;
        autoindex on;
        index index.html;

        types {
            text/html                html htm;
            text/css                 css;
            application/javascript   js mjs;
            application/json         json;
            image/png                png;
            image/jpeg               jpg jpeg;
            image/gif                gif;
            image/svg+xml            svg;
            application/pdf          pdf;
            font/woff2               woff2;
            font/woff                woff;
            application/octet-stream ttf otf;
        }
    }

    # ── Tower (default — must be last) ──
    location / {
        proxy_pass http://localhost:32354;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;
}

async function deployNginx(manifest) {
  const config = generateNginxConfig(manifest);
  const tmpPath = '/tmp/pub-hub-nginx.conf';
  const nginxConfPath = getNginxConfPath();
  fs.writeFileSync(tmpPath, config);

  // Test before applying
  const test = await run(`sudo cp ${tmpPath} ${nginxConfPath} && sudo nginx -t`);
  if (!test.ok) {
    // Restore backup
    await run(`sudo cp /tmp/pub-hub-nginx.bak ${nginxConfPath} 2>/dev/null`);
    return { ok: false, error: 'nginx config test failed', detail: test.stderr };
  }

  const reload = await run('sudo nginx -s reload');
  return { ok: reload.ok, config };
}

// ════════════════════════════════════════════════════════════
// Systemd Service Management
// ════════════════════════════════════════════════════════════

function generateServiceFile(app) {
  const workDir = app.working_dir || path.join(PUBLISHED_DIR, 'apps', app.name);
  const execStart = app.exec || (app.runtime === 'python'
    ? `/usr/bin/python3 ${workDir}/server.py`
    : `/usr/bin/node ${workDir}/server.js`);

  return `[Unit]
Description=${app.description || app.name}
After=network.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${workDir}
ExecStart=${execStart}
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
`;
}

async function installService(app) {
  const name = svcName(app.name);
  const content = generateServiceFile(app);
  const tmpPath = `/tmp/${name}`;
  fs.writeFileSync(tmpPath, content);

  const result = await run(
    `sudo cp ${tmpPath} /etc/systemd/system/${name} && sudo systemctl daemon-reload && sudo systemctl enable ${name}`
  );
  return result;
}

async function removeService(appName) {
  const name = svcName(appName);
  await run(`sudo systemctl stop ${name} 2>/dev/null`);
  await run(`sudo systemctl disable ${name} 2>/dev/null`);
  await run(`sudo rm /etc/systemd/system/${name} 2>/dev/null && sudo systemctl daemon-reload`);
  return { ok: true };
}

async function serviceAction(appName, action) {
  const name = svcName(appName);
  if (action === 'status') {
    const result = await run(`systemctl is-active ${name} 2>/dev/null`);
    return { status: result.stdout || 'unknown' };
  }
  const result = await run(`sudo systemctl ${action} ${name}`);
  return { ok: result.ok, error: result.ok ? null : result.stderr };
}

async function getServiceLogs(appName, lines = 80) {
  const name = svcName(appName);
  const result = await run(`journalctl -u ${name} -n ${lines} --no-pager 2>/dev/null`);
  return result.stdout || 'No logs available';
}

// ════════════════════════════════════════════════════════════
// Full Deploy: register app → install service → deploy nginx
// ════════════════════════════════════════════════════════════

async function fullDeploy(app, manifest) {
  const steps = [];

  // 1. Install systemd service (if managed)
  if (app.managed !== false) {
    const svc = await installService(app);
    steps.push({ step: 'systemd-install', ...svc });

    // Start service
    const start = await serviceAction(app.name, 'start');
    steps.push({ step: 'systemd-start', ...start });
  }

  // 2. Deploy nginx config
  const nginx = await deployNginx(manifest);
  steps.push({ step: 'nginx-deploy', ok: nginx.ok, error: nginx.error });

  return { ok: steps.every(s => s.ok !== false), steps };
}

// ════════════════════════════════════════════════════════════
// Sync: ensure manifest matches infra reality
// ════════════════════════════════════════════════════════════

async function syncAll() {
  const manifest = readManifest();
  const results = [];

  for (const app of manifest.apps) {
    if (app.managed === false) continue;

    // Check if service exists
    const exists = await run(`systemctl cat ${svcName(app.name)} 2>/dev/null`);
    if (!exists.ok) {
      const install = await installService(app);
      results.push({ app: app.name, action: 'install-service', ...install });
    }

    // Check if running
    const status = await serviceAction(app.name, 'status');
    if (status.status !== 'active') {
      const start = await serviceAction(app.name, 'start');
      results.push({ app: app.name, action: 'start', ...start });
    }
  }

  // Redeploy nginx
  const nginx = await deployNginx(manifest);
  results.push({ action: 'nginx-deploy', ...nginx });

  // Clean up empty site dirs
  const sitesDir = path.join(PUBLISHED_DIR, 'sites');
  if (fs.existsSync(sitesDir)) {
    for (const dir of fs.readdirSync(sitesDir)) {
      const full = path.join(sitesDir, dir);
      if (!fs.statSync(full).isDirectory()) continue;
      const files = fs.readdirSync(full).filter(f => !f.startsWith('.'));
      const inManifest = manifest.sites.some(s => s.name === dir);
      if (files.length === 0 && !inManifest) {
        fs.rmdirSync(full);
        results.push({ action: 'cleanup', dir, removed: true });
      }
    }
  }

  return results;
}

// ════════════════════════════════════════════════════════════
// Health Checks
// ════════════════════════════════════════════════════════════

function checkAppHealth(app) {
  return new Promise((resolve) => {
    if (!app.port) return resolve({ ...app, status: 'no-port', service: 'unknown' });

    // Also check systemd status
    const svc = svcName(app.name);
    exec(`systemctl is-active ${svc} 2>/dev/null`, (_, stdout) => {
      const serviceStatus = (stdout || '').trim() || 'unmanaged';

      const req = http.get(`http://localhost:${app.port}${app.health_path || '/'}`, { timeout: 3000 }, (res) => {
        resolve({ ...app, status: res.statusCode < 500 ? 'up' : 'down', statusCode: res.statusCode, service: serviceStatus });
      });
      req.on('error', () => resolve({ ...app, status: 'down', service: serviceStatus }));
      req.on('timeout', () => { req.destroy(); resolve({ ...app, status: 'timeout', service: serviceStatus }); });
    });
  });
}

function checkSiteExists(site) {
  const dir = path.join(PUBLISHED_DIR, 'sites', site.name);
  const exists = fs.existsSync(dir);
  const files = exists ? fs.readdirSync(dir).filter(f => !f.startsWith('.')).length : 0;
  return {
    ...site,
    status: exists && files > 0 ? 'live' : (exists ? 'empty' : 'missing'),
    files,
  };
}

function getRecentStats() {
  return new Promise((resolve) => {
    exec(
      'tail -1000 /var/log/nginx/access.log 2>/dev/null | grep -E "/sites/|/hub/|/edge/|/pulse/|/okusystem/" | awk \'{print $7}\' | sed \'s/\\?.*//' + '\' | sort | uniq -c | sort -rn | head -20',
      (err, stdout) => {
        if (err) return resolve([]);
        const lines = stdout.trim().split('\n').filter(Boolean);
        resolve(lines.map(l => {
          const m = l.trim().match(/^(\d+)\s+(.+)/);
          return m ? { hits: parseInt(m[1]), path: m[2] } : null;
        }).filter(Boolean));
      }
    );
  });
}

// ════════════════════════════════════════════════════════════
// Dashboard HTML
// ════════════════════════════════════════════════════════════

function dashboardHTML() {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Publishing Hub</title>
<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css" rel="stylesheet">
<style>
  :root {
    --bg: #0a0a0b; --surface: #141416; --surface2: #1c1c1f;
    --border: #2a2a2e; --text: #e4e4e7; --dim: #71717a;
    --amber: #f59e0b; --green: #22c55e; --red: #ef4444; --blue: #3b82f6;
    --radius: 12px;
  }
  * { margin:0; padding:0; box-sizing:border-box; }
  body {
    font-family: 'Pretendard Variable', -apple-system, sans-serif;
    background: var(--bg); color: var(--text);
    min-height: 100vh; padding: 24px;
  }

  /* Header */
  .header {
    display: flex; align-items: center; gap: 16px;
    margin-bottom: 32px; padding-bottom: 20px;
    border-bottom: 1px solid var(--border);
  }
  .header h1 { font-size: 24px; font-weight: 700; }
  .header .badge {
    background: var(--amber); color: #000; font-size: 11px;
    padding: 2px 8px; border-radius: 999px; font-weight: 600;
  }
  .header .v2 {
    background: var(--green); color: #000; font-size: 10px;
    padding: 2px 6px; border-radius: 999px; font-weight: 600;
  }

  /* Stats */
  .stats-bar { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
  .stat-card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: var(--radius); padding: 16px 20px; flex: 1; min-width: 120px;
  }
  .stat-card .label { font-size: 12px; color: var(--dim); margin-bottom: 4px; }
  .stat-card .value { font-size: 28px; font-weight: 700; }

  /* Sections */
  .section { margin-bottom: 32px; }
  .section-title {
    font-size: 14px; font-weight: 600; color: var(--dim);
    text-transform: uppercase; letter-spacing: 1px;
    margin-bottom: 12px; display: flex; align-items: center; gap: 8px;
  }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 12px; }

  /* Cards */
  .card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: var(--radius); padding: 20px;
    transition: border-color .2s; position: relative;
  }
  .card:hover { border-color: var(--amber); }
  .card .name {
    font-size: 16px; font-weight: 600; margin-bottom: 4px;
    display: flex; align-items: center; gap: 8px;
  }
  .card .name a { color: inherit; text-decoration: none; }
  .card .name a:hover { text-decoration: underline; }
  .card .desc { font-size: 13px; color: var(--dim); margin-bottom: 12px; }
  .card .meta { display: flex; gap: 12px; font-size: 12px; color: var(--dim); align-items: center; flex-wrap: wrap; }

  /* Status dot */
  .dot {
    display: inline-block; width: 8px; height: 8px; border-radius: 50%;
    vertical-align: middle;
  }
  .dot.up, .dot.live, .dot.active { background: var(--green); }
  .dot.down, .dot.missing, .dot.failed { background: var(--red); }
  .dot.timeout, .dot.no-port, .dot.inactive, .dot.empty { background: var(--amber); }
  .dot.unknown, .dot.unmanaged { background: var(--dim); }

  /* Access tag */
  .access-tag {
    font-size: 11px; padding: 2px 8px; border-radius: 999px;
    position: absolute; top: 12px; right: 12px; font-weight: 500;
  }
  .access-tag.public { background: rgba(34,197,94,.15); color: var(--green); }
  .access-tag.private { background: rgba(245,158,11,.15); color: var(--amber); }

  /* Buttons */
  .btn {
    background: var(--surface2); border: 1px solid var(--border); color: var(--text);
    padding: 4px 10px; border-radius: 6px; cursor: pointer; font-size: 12px;
    transition: background .2s; font-family: inherit;
  }
  .btn:hover { background: var(--border); }
  .btn.green { border-color: var(--green); color: var(--green); }
  .btn.red { border-color: var(--red); color: var(--red); }
  .btn.blue { border-color: var(--blue); color: var(--blue); }
  .btn.primary {
    background: var(--amber); color: #000; border-color: var(--amber); font-weight: 600;
  }
  .btn.primary:hover { opacity: .9; }

  .actions { display: flex; gap: 6px; margin-top: 10px; }

  /* Top actions bar */
  .top-actions { display: flex; gap: 8px; align-items: center; }

  /* Traffic table */
  .traffic-table { width: 100%; border-collapse: collapse; }
  .traffic-table th {
    text-align: left; font-size: 12px; color: var(--dim);
    padding: 8px 12px; border-bottom: 1px solid var(--border);
  }
  .traffic-table td { padding: 8px 12px; font-size: 13px; }
  .traffic-table tr:hover { background: var(--surface2); }
  .bar { height: 6px; background: var(--amber); border-radius: 3px; min-width: 4px; }

  /* Modal */
  .modal-overlay {
    display: none; position: fixed; inset: 0; background: rgba(0,0,0,.7);
    z-index: 100; justify-content: center; align-items: center;
  }
  .modal-overlay.show { display: flex; }
  .modal {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 16px; width: 90%; max-width: 700px; max-height: 80vh;
    display: flex; flex-direction: column;
  }
  .modal-header {
    display: flex; justify-content: space-between; align-items: center;
    padding: 16px 20px; border-bottom: 1px solid var(--border);
  }
  .modal-header h3 { font-size: 16px; font-weight: 600; }
  .modal-body { padding: 20px; overflow-y: auto; flex: 1; }
  .modal-footer { padding: 12px 20px; border-top: 1px solid var(--border); text-align: right; }

  /* Logs */
  .log-output {
    background: #000; color: #ccc; font-family: 'JetBrains Mono', monospace;
    font-size: 12px; padding: 16px; border-radius: 8px;
    white-space: pre-wrap; word-break: break-all;
    max-height: 400px; overflow-y: auto;
  }

  /* Form */
  .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .form-group { display: flex; flex-direction: column; gap: 4px; }
  .form-group.full { grid-column: 1 / -1; }
  .form-group label { font-size: 12px; color: var(--dim); font-weight: 500; }
  .form-group input, .form-group select {
    background: var(--bg); border: 1px solid var(--border); color: var(--text);
    padding: 8px 12px; border-radius: 8px; font-size: 13px; font-family: inherit;
  }
  .form-group input:focus, .form-group select:focus {
    outline: none; border-color: var(--amber);
  }

  .empty {
    text-align: center; padding: 40px; color: var(--dim);
    border: 1px dashed var(--border); border-radius: var(--radius);
  }

  /* Toast */
  .toast {
    position: fixed; bottom: 24px; right: 24px; z-index: 200;
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 10px; padding: 12px 20px; font-size: 13px;
    box-shadow: 0 8px 24px rgba(0,0,0,.4);
    transform: translateY(100px); opacity: 0;
    transition: all .3s ease;
  }
  .toast.show { transform: translateY(0); opacity: 1; }
  .toast.success { border-color: var(--green); }
  .toast.error { border-color: var(--red); }

  @media (max-width: 640px) {
    body { padding: 12px; }
    .grid { grid-template-columns: 1fr; }
    .form-grid { grid-template-columns: 1fr; }
  }
</style>
</head>
<body>

<div class="header">
  <h1>Publishing Hub</h1>
  <span class="badge">Hub</span>
  <span class="v2">v2</span>
  <div style="flex:1"></div>
  <span id="updated" style="font-size:12px; color:var(--dim)"></span>
  <div class="top-actions">
    <button class="btn" onclick="syncInfra()">Sync</button>
    <button class="btn" onclick="showDeployModal()">+ Deploy</button>
    <button class="btn" onclick="load()">Refresh</button>
  </div>
</div>

<div class="stats-bar" id="stats"></div>

<div class="section">
  <div class="section-title"><span>APPS</span>
    <span style="font-size:11px; color:var(--dim); text-transform:none; letter-spacing:0">Dynamic Services</span>
  </div>
  <div class="grid" id="apps-grid"></div>
</div>

<div class="section">
  <div class="section-title"><span>SITES</span>
    <span style="font-size:11px; color:var(--dim); text-transform:none; letter-spacing:0">Static HTML / Files</span>
  </div>
  <div class="grid" id="sites-grid"></div>
</div>

<div class="section">
  <div class="section-title">RECENT TRAFFIC</div>
  <table class="traffic-table">
    <thead><tr><th>Path</th><th>Hits</th><th></th></tr></thead>
    <tbody id="traffic-body"></tbody>
  </table>
</div>

<!-- Logs Modal -->
<div class="modal-overlay" id="logs-modal">
  <div class="modal">
    <div class="modal-header">
      <h3 id="logs-title">Logs</h3>
      <button class="btn" onclick="closeModal('logs-modal')">&times;</button>
    </div>
    <div class="modal-body">
      <div class="log-output" id="logs-output">Loading...</div>
    </div>
    <div class="modal-footer">
      <button class="btn" id="logs-refresh-btn">Refresh</button>
    </div>
  </div>
</div>

<!-- Deploy Modal -->
<div class="modal-overlay" id="deploy-modal">
  <div class="modal">
    <div class="modal-header">
      <h3>Deploy New App</h3>
      <button class="btn" onclick="closeModal('deploy-modal')">&times;</button>
    </div>
    <div class="modal-body">
      <div class="form-grid">
        <div class="form-group">
          <label>Name (영문, lowercase)</label>
          <input type="text" id="d-name" placeholder="my-dashboard">
        </div>
        <div class="form-group">
          <label>Port</label>
          <input type="number" id="d-port" placeholder="8380">
        </div>
        <div class="form-group full">
          <label>Description</label>
          <input type="text" id="d-desc" placeholder="My awesome dashboard">
        </div>
        <div class="form-group">
          <label>URL Path</label>
          <input type="text" id="d-path" placeholder="/my-app/">
        </div>
        <div class="form-group">
          <label>Access</label>
          <select id="d-access">
            <option value="public">Public</option>
            <option value="private">Private (login required)</option>
          </select>
        </div>
        <div class="form-group">
          <label>Runtime</label>
          <select id="d-runtime">
            <option value="node">Node.js</option>
            <option value="python">Python</option>
          </select>
        </div>
        <div class="form-group">
          <label>Health Check Path</label>
          <input type="text" id="d-health" placeholder="/" value="/">
        </div>
        <div class="form-group full">
          <label>Working Directory</label>
          <input type="text" id="d-workdir" placeholder="(auto-detected from name)">
        </div>
        <div class="form-group full">
          <label>Exec Command (optional — auto-detected from runtime)</label>
          <input type="text" id="d-exec" placeholder="/usr/bin/node server.js">
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn primary" onclick="deployApp()">Deploy</button>
    </div>
  </div>
</div>

<!-- Toast -->
<div class="toast" id="toast"></div>

<script>
const BASE = '/hub/api';

function toast(msg, type = 'success') {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.className = 'toast show ' + type;
  setTimeout(() => el.className = 'toast', 3000);
}

function closeModal(id) {
  document.getElementById(id).classList.remove('show');
}

function showDeployModal() {
  document.getElementById('deploy-modal').classList.add('show');
}

// ─── Load Dashboard ───

async function load() {
  try {
    const [manifest, health, stats] = await Promise.all([
      fetch(BASE + '/manifest').then(r => r.json()),
      fetch(BASE + '/health').then(r => r.json()),
      fetch(BASE + '/stats').then(r => r.json()).catch(() => []),
    ]);

    document.getElementById('updated').textContent =
      'Updated: ' + new Date(manifest.updated_at).toLocaleString('ko-KR');

    // Stats bar
    const totalSites = manifest.sites.length;
    const totalApps = manifest.apps.length;
    const appsUp = health.apps.filter(a => a.status === 'up').length;
    const svcsActive = health.apps.filter(a => a.service === 'active').length;
    document.getElementById('stats').innerHTML = [
      { label: 'Apps', value: totalApps },
      { label: 'Online', value: appsUp + '/' + totalApps },
      { label: 'Services', value: svcsActive + '/' + totalApps },
      { label: 'Sites', value: totalSites },
    ].map(s =>
      '<div class="stat-card"><div class="label">' + s.label + '</div><div class="value">' + s.value + '</div></div>'
    ).join('');

    // Apps
    const ag = document.getElementById('apps-grid');
    if (health.apps.length === 0) {
      ag.innerHTML = '<div class="empty">No apps registered</div>';
    } else {
      ag.innerHTML = health.apps.map(a => {
        const isSelf = a.name === 'hub';
        const managed = a.managed !== false;
        return '<div class="card">' +
          '<span class="access-tag ' + (a.access || 'public') + '">' + (a.access || 'public') + '</span>' +
          '<div class="name">' +
            '<span class="dot ' + a.status + '"></span>' +
            '<a href="' + (a.path || '/apps/' + a.name + '/') + '" target="_blank">' + a.name + '</a>' +
          '</div>' +
          '<div class="desc">' + (a.description || '') + '</div>' +
          '<div class="meta">' +
            '<span>:' + (a.port || '—') + '</span>' +
            '<span>http ' + a.status + '</span>' +
            '<span>svc ' + (a.service || '—') + '</span>' +
            (a.runtime ? '<span>' + a.runtime + '</span>' : '') +
          '</div>' +
          (managed && !isSelf ? '<div class="actions">' +
            '<button class="btn green" onclick="svcAction(\'' + a.name + '\',\'start\')">Start</button>' +
            '<button class="btn" onclick="svcAction(\'' + a.name + '\',\'restart\')">Restart</button>' +
            '<button class="btn red" onclick="svcAction(\'' + a.name + '\',\'stop\')">Stop</button>' +
            '<button class="btn blue" onclick="showLogs(\'' + a.name + '\')">Logs</button>' +
          '</div>' : '') +
        '</div>';
      }).join('');
    }

    // Sites
    const sg = document.getElementById('sites-grid');
    if (health.sites.length === 0) {
      sg.innerHTML = '<div class="empty">No sites published</div>';
    } else {
      sg.innerHTML = health.sites.map(s =>
        '<a class="card" href="/sites/' + s.name + '/" target="_blank" style="text-decoration:none; color:inherit">' +
          '<span class="access-tag ' + (s.access || 'public') + '">' + (s.access || 'public') + '</span>' +
          '<div class="name"><span class="dot ' + s.status + '"></span>' + s.name + '</div>' +
          '<div class="desc">' + (s.description || '') + '</div>' +
          '<div class="meta">' +
            '<span>' + (s.files || 0) + ' files</span>' +
            '<span>' + s.status + '</span>' +
            '<span>' + (s.created_at ? new Date(s.created_at).toLocaleDateString('ko-KR') : '') + '</span>' +
          '</div>' +
        '</a>'
      ).join('');
    }

    // Traffic
    const tb = document.getElementById('traffic-body');
    if (!stats.length) {
      tb.innerHTML = '<tr><td colspan="3" style="text-align:center; color:var(--dim)">No traffic data</td></tr>';
    } else {
      const maxHits = Math.max(...stats.map(s => s.hits));
      tb.innerHTML = stats.map(s =>
        '<tr><td style="font-family:monospace">' + s.path + '</td>' +
        '<td>' + s.hits + '</td>' +
        '<td><div class="bar" style="width:' + Math.round(s.hits / maxHits * 100) + '%"></div></td></tr>'
      ).join('');
    }
  } catch (err) {
    toast('Failed to load: ' + err.message, 'error');
  }
}

// ─── Service Actions ───

async function svcAction(name, action) {
  try {
    const res = await fetch(BASE + '/apps/' + name + '/' + action, { method: 'POST' });
    const data = await res.json();
    toast(name + ': ' + action + (data.ok ? ' OK' : ' failed'), data.ok ? 'success' : 'error');
    setTimeout(load, 1000);
  } catch (err) {
    toast(action + ' failed: ' + err.message, 'error');
  }
}

// ─── Logs ───

async function showLogs(name) {
  document.getElementById('logs-title').textContent = name + ' — Logs';
  document.getElementById('logs-output').textContent = 'Loading...';
  document.getElementById('logs-modal').classList.add('show');
  document.getElementById('logs-refresh-btn').onclick = () => showLogs(name);

  try {
    const res = await fetch(BASE + '/apps/' + name + '/logs');
    const data = await res.json();
    document.getElementById('logs-output').textContent = data.logs || 'No logs';
  } catch (err) {
    document.getElementById('logs-output').textContent = 'Error: ' + err.message;
  }
}

// ─── Deploy ───

async function deployApp() {
  const name = document.getElementById('d-name').value.trim();
  const port = parseInt(document.getElementById('d-port').value);
  if (!name || !port) { toast('Name and port required', 'error'); return; }

  const body = {
    name,
    port,
    description: document.getElementById('d-desc').value.trim(),
    path: document.getElementById('d-path').value.trim() || '/' + name + '/',
    access: document.getElementById('d-access').value,
    runtime: document.getElementById('d-runtime').value,
    health_path: document.getElementById('d-health').value.trim() || '/',
    working_dir: document.getElementById('d-workdir').value.trim() || undefined,
    exec: document.getElementById('d-exec').value.trim() || undefined,
    managed: true,
  };

  try {
    const res = await fetch(BASE + '/apps', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    const data = await res.json();
    if (data.ok) {
      toast('Deployed: ' + name, 'success');
      closeModal('deploy-modal');
      setTimeout(load, 1500);
    } else {
      toast('Deploy failed: ' + (data.error || JSON.stringify(data.steps)), 'error');
    }
  } catch (err) {
    toast('Deploy error: ' + err.message, 'error');
  }
}

// ─── Sync ───

async function syncInfra() {
  toast('Syncing infrastructure...');
  try {
    const res = await fetch(BASE + '/sync', { method: 'POST' });
    const data = await res.json();
    toast('Sync complete: ' + data.results.length + ' actions', 'success');
    setTimeout(load, 1000);
  } catch (err) {
    toast('Sync failed: ' + err.message, 'error');
  }
}

// ─── Init ───
load();
setInterval(load, 30000);
</script>
</body>
</html>`;
}

// ════════════════════════════════════════════════════════════
// HTTP Server & Routes
// ════════════════════════════════════════════════════════════

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const p = url.pathname.replace(/\/+$/, '') || '/';

  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.writeHead(204); return res.end(); }

  try {
    // ── Dashboard ──
    if (p === '' || p === '/hub' || p === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      return res.end(dashboardHTML());
    }

    // ── API: manifest ──
    if (p === '/hub/api/manifest' || p === '/api/manifest') {
      return json(res, readManifest());
    }

    // ── API: health ──
    if (p === '/hub/api/health' || p === '/api/health') {
      const m = readManifest();
      const sites = m.sites.map(checkSiteExists);
      const apps = await Promise.all(m.apps.map(checkAppHealth));
      return json(res, { sites, apps });
    }

    // ── API: stats ──
    if (p === '/hub/api/stats' || p === '/api/stats') {
      return json(res, await getRecentStats());
    }

    // ── API: sync ──
    if ((p === '/hub/api/sync' || p === '/api/sync') && req.method === 'POST') {
      const results = await syncAll();
      return json(res, { ok: true, results });
    }

    // ── API: nginx reload ──
    if ((p === '/hub/api/nginx/reload' || p === '/api/nginx/reload') && req.method === 'POST') {
      const result = await deployNginx(readManifest());
      return json(res, result);
    }

    // ── API: register app (POST) ──
    if ((p === '/hub/api/apps' || p === '/api/apps') && req.method === 'POST') {
      const body = await readBody(req);
      if (!body?.name || !body?.port) return json(res, { error: 'name and port required' }, 400);

      const m = readManifest();
      const entry = {
        name: body.name,
        port: body.port,
        path: body.path || `/${body.name}/`,
        description: body.description || '',
        access: body.access || 'public',
        health_path: body.health_path || '/',
        runtime: body.runtime || 'node',
        exec: body.exec || undefined,
        working_dir: body.working_dir || path.join(PUBLISHED_DIR, 'apps', body.name),
        managed: body.managed !== false,
        created_at: new Date().toISOString(),
      };

      const existing = m.apps.findIndex(a => a.name === body.name);
      if (existing >= 0) m.apps[existing] = { ...m.apps[existing], ...entry };
      else m.apps.push(entry);
      writeManifest(m);

      // Create app directory if needed
      if (!fs.existsSync(entry.working_dir)) {
        fs.mkdirSync(entry.working_dir, { recursive: true });
      }

      // Full deploy: systemd + nginx
      const deploy = await fullDeploy(entry, m);
      return json(res, { ok: deploy.ok, app: entry, steps: deploy.steps }, deploy.ok ? 201 : 500);
    }

    // ── API: register site (POST) ──
    if ((p === '/hub/api/sites' || p === '/api/sites') && req.method === 'POST') {
      const body = await readBody(req);
      if (!body?.name) return json(res, { error: 'name required' }, 400);

      const m = readManifest();
      const entry = {
        name: body.name,
        description: body.description || '',
        access: body.access || 'public',
        created_at: new Date().toISOString(),
      };

      const existing = m.sites.findIndex(s => s.name === body.name);
      if (existing >= 0) m.sites[existing] = { ...m.sites[existing], ...entry };
      else m.sites.push(entry);
      writeManifest(m);

      const dir = path.join(PUBLISHED_DIR, 'sites', body.name);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

      return json(res, { ok: true, site: entry }, 201);
    }

    // ── API: app actions (start/stop/restart/logs) ──
    const actionMatch = p.match(/^\/(?:hub\/)?api\/apps\/([^/]+)\/(start|stop|restart|logs)$/);
    if (actionMatch) {
      const [, appName, action] = actionMatch;

      if (action === 'logs') {
        const lines = parseInt(url.searchParams.get('lines') || '80');
        const logs = await getServiceLogs(appName, lines);
        return json(res, { logs });
      }

      const result = await serviceAction(appName, action);
      return json(res, result);
    }

    // ── API: delete app ──
    const delAppMatch = p.match(/^\/(?:hub\/)?api\/apps\/([^/]+)$/);
    if (delAppMatch && req.method === 'DELETE') {
      const name = delAppMatch[1];
      const m = readManifest();

      // Remove service
      const app = m.apps.find(a => a.name === name);
      if (app && app.managed !== false) {
        await removeService(name);
      }

      m.apps = m.apps.filter(a => a.name !== name);
      writeManifest(m);

      // Redeploy nginx
      await deployNginx(m);

      return json(res, { ok: true, deleted: name });
    }

    // ── API: delete site ──
    const delSiteMatch = p.match(/^\/(?:hub\/)?api\/sites\/([^/]+)$/);
    if (delSiteMatch && req.method === 'DELETE') {
      const name = delSiteMatch[1];
      const m = readManifest();
      m.sites = m.sites.filter(s => s.name !== name);
      writeManifest(m);
      return json(res, { ok: true, deleted: name });
    }

    json(res, { error: 'not found' }, 404);
  } catch (err) {
    console.error('[Hub Error]', err);
    json(res, { error: err.message }, 500);
  }
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`Publishing Hub v2 running on http://127.0.0.1:${PORT}`);
});
